# Generated by Django 4.1.3 on 2023-01-07 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('createTime',)},
        ),
        migrations.AlterModelOptions(
            name='classify',
            options={'ordering': ('createTime',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed78a35f-0231-4ac7-b8cd-99707142d198'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classify',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72cb1682-dad0-4904-9470-dbb79a06b566'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b7761625-11ce-41e5-90df-d6fa285e21a3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24185089-b1e6-4fe3-916e-bc0900f80848'), primary_key=True, serialize=False),
        ),
    ]
